# -*- coding: utf-8 -*-
"""m2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3gVK3vpE_n-DyOgjFDOxIauqMRbyoc8
"""

# Install required packages
!pip install nltk python-Levenshtein matplotlib torch

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
import torch.nn.functional as F
import json
import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
import nltk
import Levenshtein
from collections import Counter
import math
import random

# Download required NLTK data

nltk.download('punkt', quiet=True)
nltk.download('wordnet', quiet=True)

def encode_sentence(sentence, token2id, is_urdu=True):
    """Encode a sentence using greedy longest-match subword tokenization."""
    tokens = []

    if is_urdu:
        words = ["_" + w for w in sentence.split()]
    else:
        words = [w + "_" for w in sentence.split()]

    for w in words:
        i = 0
        while i < len(w):
            subword = None
            for j in range(len(w), i, -1):
                piece = w[i:j]
                if piece in token2id:
                    subword = piece
                    break
            if subword is None:
                tokens.append(token2id["<unk>"])
                i += 1
            else:
                tokens.append(token2id[subword])
                i += len(subword)

    return [token2id["<sos>"]] + tokens + [token2id["<eos>"]]



class TranslationDataset(Dataset):
    def __init__(self, src_sentences, tgt_sentences, src_vocab, tgt_vocab):
        self.src_data = []
        self.tgt_data = []

        for src, tgt in zip(src_sentences, tgt_sentences):
            src_tokens = encode_sentence(src, src_vocab, is_urdu=True)
            tgt_tokens = encode_sentence(tgt, tgt_vocab, is_urdu=False)

            self.src_data.append(torch.tensor(src_tokens))
            self.tgt_data.append(torch.tensor(tgt_tokens))

    def __len__(self):
        return len(self.src_data)

    def __getitem__(self, idx):
        return self.src_data[idx], self.tgt_data[idx]


def collate_fn(batch):
    src_batch, tgt_batch = zip(*batch)

    # lengths
    max_src_len = max(len(src) for src in src_batch)
    max_tgt_len = max(len(tgt) for tgt in tgt_batch)

    # we force both to same max length
    max_len = max(max_src_len, max_tgt_len)

    # pad each sequence with 0 up to max_len
    src_padded = [F.pad(src, (0, max_len - len(src)), value=0) for src in src_batch]
    tgt_padded = [F.pad(tgt, (0, max_len - len(tgt)), value=0) for tgt in tgt_batch]

    # stack into batch tensors
    return torch.stack(src_padded), torch.stack(tgt_padded)

class Encoder(nn.Module):
    def __init__(self, vocab_size=512, embed_dim=128, hidden_dim=128, num_layers=2, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.dropout = nn.Dropout(dropout)
        self.bilstm = nn.LSTM(embed_dim, hidden_dim, num_layers,
                             dropout=dropout, bidirectional=True, batch_first=True)
        self.num_layers = num_layers
        self.hidden_dim = hidden_dim

    def forward(self, x):
        embedded = self.embedding(x)
        embedded = self.dropout(embedded)
        output, (h, c) = self.bilstm(embedded)
        return output, (h, c)

class Decoder(nn.Module):
    def __init__(self, vocab_size=512, embed_dim=256, hidden_dim=256, num_layers=4,
                 output_vocab_size=512, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, num_layers,
                           dropout=dropout, batch_first=True)
        self.linear = nn.Linear(hidden_dim, output_vocab_size)
        self.num_layers = num_layers
        self.hidden_dim = hidden_dim

        # Project encoder states to decoder dimensions
        self.h_projection = nn.Linear(256, hidden_dim)  # 256 from bidirectional encoder
        self.c_projection = nn.Linear(256, hidden_dim)

    def forward(self, x, encoder_states=None):
        embedded = self.embedding(x)
        embedded = self.dropout(embedded)

        if encoder_states is not None:
            h_enc, c_enc = encoder_states
            # Convert bidirectional encoder states to decoder format
            # h_enc: [num_layers*2, batch, hidden_dim] -> [num_layers, batch, hidden_dim*2]
            batch_size = h_enc.size(1)
            h_enc = h_enc.view(2, 2, batch_size, -1)  # [directions, layers, batch, hidden]
            c_enc = c_enc.view(2, 2, batch_size, -1)

            # Concatenate forward and backward states
            h_enc = torch.cat([h_enc[0], h_enc[1]], dim=-1)  # [layers, batch, hidden*2]
            c_enc = torch.cat([c_enc[0], c_enc[1]], dim=-1)

            # Project to decoder dimensions and repeat for all decoder layers
            h_init = self.h_projection(h_enc[-1]).unsqueeze(0).repeat(self.num_layers, 1, 1)
            c_init = self.c_projection(c_enc[-1]).unsqueeze(0).repeat(self.num_layers, 1, 1)

            initial_state = (h_init, c_init)
        else:
            initial_state = None

        output, _ = self.lstm(embedded, initial_state)
        output = self.linear(output)
        return output

class Seq2SeqModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = Encoder()
        self.decoder = Decoder()

    def forward(self, src):
        # Encoder processes source
        enc_output, enc_states = self.encoder(src)

        # Decoder processes same source sequence (as per your requirement)
        dec_output = self.decoder(src, enc_states)

        return dec_output

def load_data_and_vocab():
    """Load data and vocabularies from Google Drive"""
    base_path = "/content/drive/MyDrive/Model2/"

    # Load source and target sentences
    with open(base_path + "src_normalized.txt", 'r', encoding='utf-8') as f:
        src_sentences = [line.strip() for line in f]

    with open(base_path + "tgt_normalized.txt", 'r', encoding='utf-8') as f:
        tgt_sentences = [line.strip() for line in f]

    # Load vocabularies
    with open(base_path + "vocab_Urdu.json", 'r', encoding='utf-8') as f:
        urdu_vocab = json.load(f)

    with open(base_path + "vocab_Roman.json", 'r', encoding='utf-8') as f:
        roman_vocab = json.load(f)

    return src_sentences, tgt_sentences, urdu_vocab, roman_vocab

def create_datasets(src_sentences, tgt_sentences, urdu_vocab, roman_vocab):
    """Create train/val/test splits"""
    total_size = len(src_sentences)
    train_size = int(0.7 * total_size)
    val_size = int(0.15 * total_size)

    # Shuffle data
    indices = list(range(total_size))
    random.shuffle(indices)

    train_indices = indices[:train_size]
    val_indices = indices[train_size:train_size + val_size]
    test_indices = indices[train_size + val_size:]

    # Create datasets
    train_src = [src_sentences[i] for i in train_indices]
    train_tgt = [tgt_sentences[i] for i in train_indices]

    val_src = [src_sentences[i] for i in val_indices]
    val_tgt = [tgt_sentences[i] for i in val_indices]

    test_src = [src_sentences[i] for i in test_indices]
    test_tgt = [tgt_sentences[i] for i in test_indices]

    train_dataset = TranslationDataset(train_src, train_tgt, urdu_vocab, roman_vocab)
    val_dataset = TranslationDataset(val_src, val_tgt, urdu_vocab, roman_vocab)
    test_dataset = TranslationDataset(test_src, test_tgt, urdu_vocab, roman_vocab)

    return train_dataset, val_dataset, test_dataset

def calculate_perplexity(loss):
    """Calculate perplexity from loss"""
    return math.exp(loss)

def decode_tokens(tokens, id2token):
    """Convert token IDs back to text"""
    words = []
    for token_id in tokens:
        if token_id in [0, 1, 2]:  # pad, sos, eos
            continue
        words.append(id2token.get(token_id, '<unk>'))
    return ' '.join(words)

def calculate_bleu(reference, hypothesis):
    """Calculate BLEU score"""
    reference_tokens = reference.split()
    hypothesis_tokens = hypothesis.split()

    if len(hypothesis_tokens) == 0:
        return 0.0

    smoothie = SmoothingFunction().method4
    return sentence_bleu([reference_tokens], hypothesis_tokens, smoothing_function=smoothie)

def calculate_cer(reference, hypothesis):
    """Calculate Character Error Rate"""
    if len(reference) == 0:
        return 1.0 if len(hypothesis) > 0 else 0.0
    return Levenshtein.distance(reference, hypothesis) / len(reference)

def calculate_edit_distance(reference, hypothesis):
    """Calculate Levenshtein distance"""
    return Levenshtein.distance(reference, hypothesis)

def train_model(model, train_loader, val_loader, criterion, optimizer, epochs, device, roman_vocab):
    id2roman = {v: k for k, v in roman_vocab.items()}

    for epoch in range(epochs):
        # ---- TRAINING ----
        model.train()
        total_loss = 0
        correct, total = 0, 0

        for batch_idx, (src, tgt) in enumerate(train_loader):
            src, tgt = src.to(device), tgt.to(device)

            optimizer.zero_grad()
            output = model(src)  # (batch, seq_len, vocab_size)

            # Flatten for CE Loss
            output_flat = output.reshape(-1, output.size(-1))
            tgt_flat = tgt.reshape(-1)

            loss = criterion(output_flat, tgt_flat)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()

            # Accuracy (token-level)
            predictions = torch.argmax(output, dim=-1)
            correct += (predictions == tgt).sum().item()
            total += tgt.numel()

        avg_train_loss = total_loss / len(train_loader)
        train_perplexity = calculate_perplexity(avg_train_loss)
        train_accuracy = correct / total

        # ---- VALIDATION ----
        model.eval()
        val_loss, val_bleu, val_cer, val_edit, val_correct, val_total = 0, 0, 0, 0, 0, 0

        with torch.no_grad():
            for src, tgt in val_loader:
                src, tgt = src.to(device), tgt.to(device)
                output = model(src)

                # Loss
                output_flat = output.reshape(-1, output.size(-1))
                tgt_flat = tgt.reshape(-1)
                loss = criterion(output_flat, tgt_flat)
                val_loss += loss.item()

                # Predictions
                predictions = torch.argmax(output, dim=-1)
                val_correct += (predictions == tgt).sum().item()
                val_total += tgt.numel()

                for i in range(src.size(0)):
                    pred_tokens = predictions[i].cpu().numpy()
                    tgt_tokens = tgt[i].cpu().numpy()

                    pred_text = decode_tokens(pred_tokens, id2roman)
                    ref_text = decode_tokens(tgt_tokens, id2roman)

                    val_bleu += calculate_bleu(ref_text, pred_text)
                    val_cer += calculate_cer(ref_text, pred_text)
                    val_edit += calculate_edit_distance(ref_text, pred_text)

        # Averages
        avg_val_loss = val_loss / len(val_loader)
        val_perplexity = calculate_perplexity(avg_val_loss)
        avg_val_bleu = val_bleu / len(val_loader.dataset)
        avg_val_cer = val_cer / len(val_loader.dataset)
        avg_val_edit = val_edit / len(val_loader.dataset)
        val_accuracy = val_correct / val_total

        # ---- RESULTS ----
        print(f"\nEpoch {epoch+1}/{epochs}")
        print(f"Train Loss: {avg_train_loss:.4f}, Perplexity: {train_perplexity:.4f}, Accuracy: {train_accuracy:.4f}")
        print(f"Val Loss:   {avg_val_loss:.4f}, Perplexity: {val_perplexity:.4f}, "
              f"Accuracy: {val_accuracy:.4f}, BLEU: {avg_val_bleu:.4f}, CER: {avg_val_cer:.4f}, "
              f"Edit Dist: {avg_val_edit:.2f}")




def evaluate_model(model, test_loader, roman_vocab, device):
    """Evaluate model with metrics"""
    model.eval()
    id2roman = {v: k for k, v in roman_vocab.items()}

    total_bleu = 0
    total_cer = 0
    total_edit_dist = 0
    total_loss = 0
    count = 0

    criterion = nn.CrossEntropyLoss(ignore_index=0)

    with torch.no_grad():
        for src, tgt in test_loader:
            src, tgt = src.to(device), tgt.to(device)

            output = model(src)

            # Calculate loss
            loss_output_flat = output.reshape(-1, output.size(-1))
            target_flat = tgt.reshape(-1)
            loss = criterion(loss_output_flat, target_flat)
            total_loss += loss.item()

            predictions = torch.argmax(output, dim=-1)

            for i in range(src.size(0)):
                pred_tokens = predictions[i].cpu().numpy()
                tgt_tokens = tgt[i].cpu().numpy()

                pred_text = decode_tokens(pred_tokens, id2roman)
                ref_text = decode_tokens(tgt_tokens, id2roman)

                total_bleu += calculate_bleu(ref_text, pred_text)
                total_cer += calculate_cer(ref_text, pred_text)
                total_edit_dist += calculate_edit_distance(ref_text, pred_text)
                count += 1

    avg_loss = total_loss / len(test_loader)
    avg_bleu = total_bleu / count
    avg_cer = total_cer / count
    avg_edit_dist = total_edit_dist / count

    print(f"Test Loss: {avg_loss:.4f}, Perplexity: {calculate_perplexity(avg_loss):.4f}")
    print(f"BLEU Score: {avg_bleu:.4f}")
    print(f"Character Error Rate: {avg_cer:.4f}")
    print(f"Average Edit Distance: {avg_edit_dist:.2f}")

    return avg_bleu, avg_cer, avg_edit_dist

def show_examples(model, test_dataset, urdu_vocab, roman_vocab, device, num_examples=5):
    """Show translation examples"""
    model.eval()
    id2roman = {v: k for k, v in roman_vocab.items()}
    id2urdu = {v: k for k, v in urdu_vocab.items()}

    indices = random.sample(range(len(test_dataset)), num_examples)

    with torch.no_grad():
        for idx in indices:
            src, tgt = test_dataset[idx]
            src_batch = src.unsqueeze(0).to(device)

            output = model(src_batch)
            prediction = torch.argmax(output, dim=-1).squeeze(0)

            src_text = decode_tokens(src.numpy(), id2urdu)
            tgt_text = decode_tokens(tgt.numpy(), id2roman)
            pred_text = decode_tokens(prediction.cpu().numpy(), id2roman)

            print(f"Source (Urdu): {src_text}")
            print(f"Target (Roman): {tgt_text}")
            print(f"Prediction: {pred_text}")

            # Calculate metrics for this example
            bleu = calculate_bleu(tgt_text, pred_text)
            cer = calculate_cer(tgt_text, pred_text)
            edit_dist = calculate_edit_distance(tgt_text, pred_text)

            print(f"BLEU: {bleu:.3f}, CER: {cer:.3f}, Edit Dist: {edit_dist}")
            print("-" * 50)

def test_metrics_sanity_check():
    """Sanity check for evaluation metrics"""
    print("Testing evaluation metrics...")

    # Test BLEU
    ref = "yeh ek test sentence hai"
    hyp = "yeh ek test sentence hai"
    print(f"BLEU (identical): {calculate_bleu(ref, hyp):.4f}")

    hyp = "yeh test sentence hai"
    print(f"BLEU (missing word): {calculate_bleu(ref, hyp):.4f}")

    # Test CER
    ref = "hello world"
    hyp = "hello world"
    print(f"CER (identical): {calculate_cer(ref, hyp):.4f}")

    hyp = "helo wrold"
    print(f"CER (2 errors): {calculate_cer(ref, hyp):.4f}")

    # Test Edit Distance
    print(f"Edit distance (identical): {calculate_edit_distance('hello', 'hello')}")
    print(f"Edit distance (1 substitution): {calculate_edit_distance('hello', 'hallo')}")

test_metrics_sanity_check()

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load data
src_sentences, tgt_sentences, urdu_vocab, roman_vocab = load_data_and_vocab()

# Create datasets
train_dataset, val_dataset, test_dataset = create_datasets(
    src_sentences, tgt_sentences, urdu_vocab, roman_vocab)

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, collate_fn=collate_fn)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, collate_fn=collate_fn)

# Initialize model
model = Seq2SeqModel().to(device)
criterion = nn.CrossEntropyLoss(ignore_index=0)  # Ignore padding

# Show examples
print("\nTranslation Examples:")
show_examples(model, test_dataset, urdu_vocab, roman_vocab, device)

print("Starting training...")

# Step 1: Train encoder only (freeze decoder)
print("\nStep 1: Training encoder (5 epochs)")
for param in model.decoder.parameters():
    param.requires_grad = False

optimizer = optim.Adam([p for p in model.parameters() if p.requires_grad], lr=0.001)

train_model(model, train_loader, val_loader, criterion, optimizer, 10, device, roman_vocab)

# Show examples
print("\nTranslation Examples:")
show_examples(model, test_dataset, urdu_vocab, roman_vocab, device)

# Step 2: Train decoder only (freeze encoder)
print("\nStep 2: Training decoder (10 epochs)")
for param in model.encoder.parameters():
    param.requires_grad = False
for param in model.decoder.parameters():
    param.requires_grad = True

optimizer = optim.Adam([p for p in model.parameters() if p.requires_grad], lr=0.001)
train_model(model, train_loader, val_loader, criterion, optimizer, 15, device,roman_vocab)

# Show examples
print("\nTranslation Examples:")
show_examples(model, test_dataset, urdu_vocab, roman_vocab, device)

#more 10 epochs
# Step 2: Train decoder only (freeze encoder)
print("\nStep 2: Training decoder (10 epochs)")
for param in model.encoder.parameters():
    param.requires_grad = False
for param in model.decoder.parameters():
    param.requires_grad = True

optimizer = optim.Adam([p for p in model.parameters() if p.requires_grad], lr=0.001)
train_model(model, train_loader, val_loader, criterion, optimizer, 10, device,roman_vocab)

# Step 3: Train full model
print("\nStep 3: Training full model (10 epochs)")
for param in model.parameters():
    param.requires_grad = True

optimizer = optim.Adam(model.parameters(), lr=0.0005)
train_model(model, train_loader, val_loader, criterion, optimizer, 20, device,roman_vocab)

# Show examples
print("\nTranslation Examples:")
show_examples(model, test_dataset, urdu_vocab, roman_vocab, device)

# Step 4: Fine-tune with low learning rate and decay
print("\nStep 4: Fine-tuning with learning rate decay (10 epochs)")
optimizer = optim.Adam(model.parameters(), lr=0.0001)
scheduler = optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.9)

for epoch in range(10):
    train_model(model, train_loader, val_loader, criterion, optimizer, 1, device, roman_vocab)
    scheduler.step()
    print(f"Learning rate: {scheduler.get_last_lr()[0]:.6f}")

# Show examples
print("\nTranslation Examples:")
show_examples(model, test_dataset, urdu_vocab, roman_vocab, device)

# Evaluation
print("\nEvaluation Results:")
evaluate_model(model, test_loader, roman_vocab, device)

# Show examples
print("\nTranslation Examples:")
show_examples(model, test_dataset, urdu_vocab, roman_vocab, device)

save_path = "/content/drive/MyDrive/Model2/urdu_roman_nmt_model.pth"
# Save model
torch.save({
    'model_state_dict': model.state_dict(),
    'urdu_vocab': urdu_vocab,
    'roman_vocab': roman_vocab
}, save_path)
print("Model saved as 'urdu_roman_nmt_model.pth'")

